import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
	variable: "--font-geist-sans",
	subsets: ["latin"],
});

const geistMono = Geist_Mono({
	variable: "--font-geist-mono",
	subsets: ["latin"],
});

export const metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({ children }) {
	const variable = `${geistSans.variable} ${geistMono.variable}`;
	return (
		<html lang="en">
			<body className={`${variable} antialiased`}>{children}</body>
		</html>
	);
}
